In [1]:
#integers
x=1
type(x)

int

In [2]:
i=3
if i<3 :
    print("i is less than 3")
elif i<5 :
    print("i is less than 5")
else:
    print("i is 5 or more")
   

i is less than 5


In [4]:
#Since which program to be executed not mentioned, picked up the code from the snapshot in the Course Material Document and executed
import numpy as np
np.random.seed(0) #seed for reproducibility
x1 = np.random.randint(10,size=6) #one-dimensional array
x2 = np.random.randint(10,size=(3,4)) #two-dimensional array
x3 = np.random.randint(10,size=(3,4,5)) #three dimensional array


In [5]:
print (x1)
print (x2)
print (x3)


[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
